version: 2

project_name: lalibela

before:
  hooks:
    - go mod tidy

builds:
  - id: lalibela
    main: ./cmd/lalibela
    binary: lalibela
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.GitCommit={{.ShortCommit}} -X main.BuildDate={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: auto
